require "import"

import "org.jsoup.*"

import "androidx.appcompat.widget.*"
import "androidx.appcompat.app.*"
import "androidx.appcompat.view.*"

import "android.widget.*"
import "android.app.*"
import "android.os.*"
import "android.view.*"
import "android.view.inputmethod.InputMethodManager"
import "android.content.*"
import "android.graphics.*"
import "android.content.res.ColorStateList"
import "android.graphics.PorterDuff"

import "android.graphics.Bitmap"
import "android.graphics.Color"
import "android.graphics.Typeface"
import "android.graphics.drawable.GradientDrawable"

import "androidx.constraintlayout.widget.ConstraintLayout"
import "androidx.coordinatorlayout.widget.CoordinatorLayout"
import "androidx.swiperefreshlayout.widget.SwipeRefreshLayout"
import "androidx.cardview.widget.CardView"

import "androidx.recyclerview.widget.RecyclerView"
import "androidx.recyclerview.widget.StaggeredGridLayoutManager"

import "androidx.core.view.WindowInsetsCompat"
import "androidx.core.view.WindowCompat"
import "androidx.core.view.WindowInsetsCompat"
import "androidx.core.view.WindowInsetsControllerCompat"
import "androidx.core.graphics.ColorUtils"

import "android.animation.LayoutTransition"

import "android.net.Uri"
import "android.content.Intent"
import "android.content.Context"
import "android.content.res.Configuration"
import "android.content.res.ColorStateList"

import "com.google.android.material.tabs.TabLayout"
import "com.google.android.material.card.MaterialCardView"
import "com.google.android.material.button.MaterialButton"
import "com.google.android.material.snackbar.Snackbar"
import "com.google.android.material.textfield.TextInputEditText"
import "com.google.android.material.textfield.TextInputLayout"
import "com.google.android.material.dialog.MaterialAlertDialogBuilder"
import "com.google.android.material.progressindicator.CircularProgressIndicator"
import "com.google.android.material.elevation.ElevationOverlayProvider"
import "com.google.android.material.color.MaterialColors"

import "java.io.File"
import "java.io.FileInputStream"
import "java.io.FileOutputStream"

import "com.androlua.LuaUtil"
import "com.androlua.network.LuaHttp"
import "com.androlua.fragment.LuaFragment"
import "com.androlua.fragment.LuaFragment"
import "com.androlua.fragment.LuaFragment$FragmentCreator"
import "com.androlua.adapter.*"
import "com.androlua.adapter.LuaRecyclerAdapter"
import "com.androlua.adapter.LuaRecyclerAdapter$AdapterCreator"
import "com.androlua.adapter.LuaRecyclerHolder"
import "com.androlua.adapter.LuaAdapter"