name: Build Debug App
on:
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            $ {{ runner.os }}-gradle-
      - name: Making Copy of Lua files
        run: mkdir -p app/src/main/assets && mkdir -p app/src/main/lua && mkdir -p androlua/src/main/assets && mkdir -p androlua/src/main/lua &&
          cp -r app/src/main/assets_bin/* > app/src/main/assets/ &&
          cp -r app/src/main/luaLibs/* > app/src/main/lua/ &&
          cp -r androlua/src/main/assets_bin/* > androlua/src/main/assets/ &&
          cp -r androlua/src/main/luaLibs/* > androlua/src/main/lua/
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Assemble debug
        run: ./gradlew assembledebug
      - name: Upload build Debug
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/**.apk
          if-no-files-found: error