name: Build Debug App
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build --scan
    - name: Upload build Debug
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/debug/
        if-no-files-found: error